/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PlacesTEC.capaPresentacion.main;

import PlacesTEC.capaLogica.logica.GestionLugares;

/**
 *
 * @author sebas
 */
public class Principal extends javax.swing.JFrame {
    private GestionLugares destinos;

    public GestionLugares getDestinos() {
        return destinos;
    }

    public void setDestinos(GestionLugares destinos) {
        this.destinos = destinos;
    }
    
    

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jButtonGesLug = new javax.swing.JButton();
        jButtonSitiosInt = new javax.swing.JButton();
        jButtonRutaViaje = new javax.swing.JButton();
        jButtonRutaCorta = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTitulo.setText("Places TEC");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jButtonGesLug.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonGesLug.setText("Gestionar lugares destino");
        jButtonGesLug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGesLugActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGesLug, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, 90));

        jButtonSitiosInt.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonSitiosInt.setText("Sitios de interés cercanos");
        jButtonSitiosInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSitiosIntActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSitiosInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, 90));

        jButtonRutaViaje.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonRutaViaje.setText("Armar una ruta de viaje");
        getContentPane().add(jButtonRutaViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 510, 80));

        jButtonRutaCorta.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonRutaCorta.setText(" Recomendación de viaje más corto");
        jButtonRutaCorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRutaCortaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRutaCorta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 660, -1, 80));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlacesTEC/capaPresentacion/main/526791.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-145, 0, 1210, 824));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSitiosIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSitiosIntActionPerformed
        VentSitios crearSit = new VentSitios(this, rootPaneCheckingEnabled,this,destinos);
        crearSit.setVisible(true);
        crearSit.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_jButtonSitiosIntActionPerformed

    private void jButtonRutaCortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRutaCortaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRutaCortaActionPerformed

    private void jButtonGesLugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGesLugActionPerformed
      VentGestDestinos crear_VentDest = new VentGestDestinos(this, rootPaneCheckingEnabled,this);
       crear_VentDest.setVisible(true);
       crear_VentDest.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_jButtonGesLugActionPerformed

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGesLug;
    private javax.swing.JButton jButtonRutaCorta;
    private javax.swing.JButton jButtonRutaViaje;
    private javax.swing.JButton jButtonSitiosInt;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
}
