/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PlacesTEC.capaPresentacion.main;

/**
 *
 * @author sebas
 */
public class VentAddLatLon extends javax.swing.JDialog {
    private VentGestDestinos ventgestion_destinos;

    /**
     * Creates new form VentAddLatLon
     */
    public VentAddLatLon(java.awt.Dialog parent, boolean modal,VentGestDestinos ventgestion_destinos) {
        super(parent, modal);
        initComponents();
        this.ventgestion_destinos = ventgestion_destinos;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelLat = new javax.swing.JLabel();
        jLabelLon = new javax.swing.JLabel();
        jLabelModo = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jButtonAgreLug = new javax.swing.JButton();
        jTextFieldLat = new javax.swing.JTextField();
        jTextFieldLon = new javax.swing.JTextField();
        jTextFieldmodo = new javax.swing.JTextField();
        jTextFieldFecha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Registar Lugar de destino");

        jLabelLat.setText("Latitud:");

        jLabelLon.setText("Longitud:");

        jLabelModo.setText("Modo de desplazamiento:");

        jLabelFecha.setText("Fecha tentativa de visita:");

        jButtonAgreLug.setText("Agregar Lugar");
        jButtonAgreLug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgreLugActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelFecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldFecha))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelModo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldmodo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldLon))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldLat, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jButtonAgreLug, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLat)
                    .addComponent(jTextFieldLat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLon)
                    .addComponent(jTextFieldLon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModo)
                    .addComponent(jTextFieldmodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha)
                    .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButtonAgreLug, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgreLugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgreLugActionPerformed
       String modo;
       String fecha;
       int Lat,Lon;
       
       Lat = Integer.parseInt(this.jTextFieldLat.getText());
       Lon = Integer.parseInt(this.jTextFieldLon.getText());
       modo = this.jTextFieldmodo.getText();
       fecha = this.jTextFieldFecha.getText();
        
        ventgestion_destinos.getPrincipal().getDestinos().agregarLugarLatLon(Lat,Lon, fecha, modo);
        System.out.println(ventgestion_destinos.getPrincipal().getDestinos().toString());
        this.dispose();
        
    }//GEN-LAST:event_jButtonAgreLugActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgreLug;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelLat;
    private javax.swing.JLabel jLabelLon;
    private javax.swing.JLabel jLabelModo;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldLat;
    private javax.swing.JTextField jTextFieldLon;
    private javax.swing.JTextField jTextFieldmodo;
    // End of variables declaration//GEN-END:variables
}
