/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PlacesTEC.capaPresentacion.main;

import PlacesTEC.capaLogica.logica.GestionLugares;

/**
 *
 * @author sebas
 */
public class VentGestDestinos extends javax.swing.JDialog {
    private Principal principal;
    private GestionLugares lugares;

    public GestionLugares getLugares() {
        return lugares;
    }

    public void setLugares(GestionLugares lugares) {
        this.lugares = lugares;
    }
    
    

    public Principal getPrincipal() {
        return principal;
    }

    public void setPrincipal(Principal principal) {
        this.principal = principal;
    }
    
    

    /**
     * Creates new form VentGestDestinos
     */
    public VentGestDestinos(java.awt.Frame parent, boolean modal,Principal principal) {
        super(parent, modal);
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jButtonRegDir = new javax.swing.JButton();
        jButtonRegLatLon = new javax.swing.JButton();
        jButtonEditarDes = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTitulo.setText("Gestionar lugares destino");

        jButtonRegDir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonRegDir.setText("Registar lugar por dirección exacta");
        jButtonRegDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegDirActionPerformed(evt);
            }
        });

        jButtonRegLatLon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonRegLatLon.setText("Registar lugar por latitud y longitud");
        jButtonRegLatLon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegLatLonActionPerformed(evt);
            }
        });

        jButtonEditarDes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonEditarDes.setText("Editar Lugar de destino");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Eliminar Lugar de destino");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonRegDir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                            .addComponent(jButtonRegLatLon)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEditarDes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelTitulo)
                .addGap(51, 51, 51)
                .addComponent(jButtonRegDir, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButtonRegLatLon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonEditarDes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegDirActionPerformed
        VentAddDir crear_lugar = new VentAddDir(this, rootPaneCheckingEnabled, this);
        crear_lugar.setVisible(true);
        crear_lugar.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

    }//GEN-LAST:event_jButtonRegDirActionPerformed

    private void jButtonRegLatLonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegLatLonActionPerformed
       VentAddLatLon crear_lugar = new VentAddLatLon(this, rootPaneCheckingEnabled, this);
        crear_lugar.setVisible(true);
        crear_lugar.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

    }//GEN-LAST:event_jButtonRegLatLonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEditarDes;
    private javax.swing.JButton jButtonRegDir;
    private javax.swing.JButton jButtonRegLatLon;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
}
