/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package virtuallibrarytec.capaPresentacion.main;


import virtuallibrarytec.capaLogica.utils.ModeladorTablas;
import javax.swing.JTable;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import virtuallibrarytec.capaLogica.estructuras.Nodo;
import virtuallibrarytec.capaLogica.estructuras.NodoD;
import virtuallibrarytec.capaLogica.estructuras.NodoS;
import virtuallibrarytec.capaLogica.logicaNeogicos.Cliente;
import virtuallibrarytec.capaLogica.logicaNeogicos.GestionClientesPedidos;
import virtuallibrarytec.capaLogica.logicaNeogicos.GestionLibros;
import virtuallibrarytec.capaLogica.logicaNeogicos.Libreria;
import virtuallibrarytec.capaLogica.logicaNeogicos.Libro;
import virtuallibrarytec.capaLogica.logicaNeogicos.Pedido;

/**
 *
 * @author sebas
 */
public class VentVerClientes extends javax.swing.JDialog {
    
    private GestionClientesPedidos clientes;
    private VentAtencionPedidos ventAteP;

    public GestionClientesPedidos getClientes() {
        return clientes;
    }

    public void setClientes(GestionClientesPedidos clientes) {
        this.clientes = clientes;
    }

    public VentAtencionPedidos getVentAteP() {
        return ventAteP;
    }

    public void setVentAteP(VentAtencionPedidos ventAteP) {
        this.ventAteP = ventAteP;
    }

   
    
    
    public JTable getTabla_Libros() {
        return Tabla_Libros;
    }

    public void setTabla_Libros(JTable Tabla_Libros) {
        this.Tabla_Libros = Tabla_Libros;
    }

    
    
    

    /**
     * Creates new form VentGestion_Vehiculos
     * @param parent
     * @param modal
     * @param principal
     */
    public VentVerClientes(java.awt.Dialog parent, boolean modal, VentAtencionPedidos ventAteP) {
        super(parent,modal);
        initComponents();
        this.ventAteP = ventAteP;
        
    }

    /**
     *
     */
    public void actualizarTabla(Cliente elemento) {
        if (elemento.getLibros_compra().esVacia()) {
            ModeladorTablas.vaciarTabla(Tabla_Libros);
        } else {
            ModeladorTablas.vaciarTabla(Tabla_Libros);
            Object[] filaNueva;
            NodoS <Libro> temp = elemento.getLibros_compra().getCabeza();
            for (int i = 0; i < elemento.getLibros_compra().getTamano(); i++) {
                filaNueva = new Object[]{temp.getContiene().getID(),temp.getContiene().getNombre(),temp.getContiene().getTema(),
                    temp.getContiene().getDescripcion(),temp.getContiene().getPrecio()};
                ModeladorTablas.nuevaFila(Tabla_Libros, filaNueva);
                temp = temp.getSiguiente();
            }

        }
    }

    /**
     *
     * @throws Exception
     */
    public void eliminarDesdeTabla() throws Exception {
        
        this.busCliente().getLibros_compra().eliminar(Tabla_Libros.getSelectedRow());
        
        //Tabla_Agencias.remove(Tabla_Agencias.getSelectedRow());
        this.dispose();
        
        VentVerClientes crear_Libro = new VentVerClientes(ventAteP, rootPaneCheckingEnabled,ventAteP);
        
        Object[] columnasLibros = new Object[] {"ID","Nombre","Tema","Descripción","Precio"};        
        crear_Libro.getTabla_Libros().setModel(ModeladorTablas.generarModeloDeTabla(5, columnasLibros));
        crear_Libro.getTabla_Libros().setAutoCreateRowSorter(false);
        crear_Libro.actualizarTabla(busCliente());
        
        crear_Libro.setVisible(true);
        crear_Libro.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    public Cliente busCliente(){
        String cedula = this.jTextFieldCedula.getText();
      
        
            NodoS<Cliente> temp =  ventAteP.getPrincipal().getUsuarios().getLista_clientes().getCabeza();
            for (int i = 0; i < ventAteP.getPrincipal().getUsuarios().getLista_clientes().getTamano(); i++) {
                System.out.println("Entro al for"+i);
                
                if (cedula.equals(temp.getContiene().getCedula())){
                    System.out.println("entro al if de busCliente");
                    System.out.println(temp.getContiene().toString());
                    return temp.getContiene();
                    
                    
    }                                                    
           temp = temp.getSiguiente(); }
        return null;
        
        
       
        
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Libros = new javax.swing.JTable();
        jLabelTitulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFieldCedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Tabla_Libros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla_Libros);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabelTitulo.setText("Gestión de Clientes");

        jButton1.setText("Empezar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingrese la cédula del cliente para ver sus libros comprados:");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Ver Libro");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(180, 180, 180)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1019, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2))
                    .addComponent(jLabelTitulo))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jButton2)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
          
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.busCliente();
        this.actualizarTabla(this.busCliente());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int row = Tabla_Libros.getSelectedRow();
       String ID,Nombre,Tema,Descripcion, Precio;
       ID  = Tabla_Libros.getModel().getValueAt(row, 0).toString();
       Nombre = Tabla_Libros.getModel().getValueAt(row, 1).toString();
       Tema = Tabla_Libros.getModel().getValueAt(row, 2).toString();
       Descripcion =Tabla_Libros.getModel().getValueAt(row, 3).toString();
       Precio = Tabla_Libros.getModel().getValueAt(row, 4).toString();
       
       
        
        VentVerLibro verLibro = new VentVerLibro(this, rootPaneCheckingEnabled,this);
        //this.jTextFieldBusqueda.setText("");
        verLibro.getjTextFieldID().setText(ID);
        verLibro.getjTextFieldNombre().setText(Nombre);
        verLibro.getjTextFieldTema().setText(Tema);
        verLibro.getjTextFieldDescripcion().setText(Descripcion);
        verLibro.getjTextFieldPrecio().setText(Precio);
                
                
         verLibro.setVisible(true);
         verLibro.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_Libros;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCedula;
    // End of variables declaration//GEN-END:variables
}
