/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package virtuallibrarytec.capaPresentacion.main;

import javax.swing.JTable;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import virtuallibrarytec.capaLogica.estructuras.NodoD;
import virtuallibrarytec.capaLogica.estructuras.NodoS;
import virtuallibrarytec.capaLogica.logicaNeogicos.GestionBusqueda;
import virtuallibrarytec.capaLogica.logicaNeogicos.Libro;
import virtuallibrarytec.capaLogica.utils.ModeladorTablas;

/**
 *
 * @author sebas
 */
public class VentHistorial extends javax.swing.JDialog {
    private VentBusqueda busqueda;
    private GestionBusqueda historial;

    public VentBusqueda getBusqueda() {
        return busqueda;
    }

    public void setBusqueda(VentBusqueda busqueda) {
        this.busqueda = busqueda;
    }

    public GestionBusqueda getHistorial2() {
        return historial;
    }

    public void setHistorial(GestionBusqueda historial) {
        this.historial = historial;
    }

    public JTable getTablaHistorial() {
        return TablaHistorial;
    }

    public void setTablaHistorial(JTable TablaHistorial) {
        this.TablaHistorial = TablaHistorial;
    }
    
    
    

    /**
     * Creates new form VenHistorial
     */
    public VentHistorial(java.awt.Dialog parent, boolean modal,VentBusqueda busqueda) {
        super(parent, modal);
        initComponents();
        this.busqueda = busqueda;
    }
    
    
    public void actualizarTabla() {
        if (busqueda.getPrincipal().getHistorial().getHistorial2().esVacia()) {
            ModeladorTablas.vaciarTabla(TablaHistorial);
        } else {
            ModeladorTablas.vaciarTabla(TablaHistorial);
            Object[] filaNueva;
            NodoS<Libro> temp = busqueda.getPrincipal().getHistorial().getHistorial2().getCabeza();
            for (int i = 0; i < busqueda.getPrincipal().getHistorial().getHistorial2().getTamano(); i++) {
                filaNueva = new Object[]{temp.getContiene().getID(),temp.getContiene().getNombre(),
                    temp.getContiene().getTema(),temp.getContiene().getDescripcion(),temp.getContiene().getPrecio()
                    };
                ModeladorTablas.nuevaFila(TablaHistorial, filaNueva);
                temp = temp.getSiguiente();
            }

        }
    }

    /**
     *
     * @throws Exception
     */
    public void eliminarDesdeTabla() throws Exception {
         busqueda.getPrincipal().getHistorial().getHistorial2().eliminar(TablaHistorial.getSelectedRow());
        //Tabla_Agencias.remove(Tabla_Agencias.getSelectedRow());
        this.dispose();
        
        VentHistorial crear_Libro = new VentHistorial(busqueda, rootPaneCheckingEnabled,busqueda);
        
        Object[] columnasLibros = new Object[] {"ID","Nombre","Tema","Descripción","Precio"};        
        crear_Libro.getTablaHistorial().setModel(ModeladorTablas.generarModeloDeTabla(5, columnasLibros));
        crear_Libro.getTablaHistorial().setAutoCreateRowSorter(false);
        crear_Libro.actualizarTabla();
        
        crear_Libro.setVisible(true);
        crear_Libro.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaHistorial = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 85)); // NOI18N
        jLabel1.setText("Historial");

        TablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaHistorial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaHistorial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
