/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package virtuallibrarytec.capaPresentacion.main;


import virtuallibrarytec.capaLogica.utils.ModeladorTablas;
import javax.swing.JTable;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import virtuallibrarytec.capaLogica.logicaNeogicos.GestionLibros;

/**
 *
 * @author sebas
 */
public class VentGestion_Libros extends javax.swing.JDialog {
    private Principal principal;
    private GestionLibros libros;

    /**
     *
     * @return
     */
    public Principal getPrincipal() {
        return principal;
    }

    /**
     *
     * @param principal
     */
    public void setPrincipal(Principal principal) {
        this.principal = principal;
    }

    public GestionLibros getLibros() {
        return libros;
    }

    /**
     *
     * @return
     */
    public void setLibros(GestionLibros libros) {    
        this.libros = libros;
    }

    public JTable getTabla_Libros() {
        return Tabla_Libros;
    }

    public void setTabla_Libros(JTable Tabla_Libros) {
        this.Tabla_Libros = Tabla_Libros;
    }

    
    
    

    /**
     * Creates new form VentGestion_Vehiculos
     * @param parent
     * @param modal
     * @param principal
     */
    public VentGestion_Libros(java.awt.Frame parent, boolean modal, Principal principal) {
        super(parent,modal);
        initComponents();
        this.principal = principal;
        
    }

    /**
     *
     */
   /** public void actualizarTabla() {
        if (principal.getVehiculos().getLista_vehiculos().esVacia()) {
            ModeladorTablas.vaciarTabla(Tabla_Libros);
        } else {
            ModeladorTablas.vaciarTabla(Tabla_Vehiculos);
            Object[] filaNueva;
            NodoD<Vehiculo> temp = principal.getVehiculos().getLista_vehiculos().getCabeza();
            for (int i = 0; i < principal.getVehiculos().getLista_vehiculos().getTamano(); i++) {
                filaNueva = new Object[]{temp.getElemento().getMarca(),
                    temp.getElemento().getModelo(),temp.getElemento().getTipo(),temp.getElemento().getDescripcion(),temp.getElemento().getCilindrada(),temp.getElemento().getTipo_combustible(),temp.getElemento().getTransmision(),temp.getElemento().getColores(),temp.getElemento().getLista_extras(),temp.getElemento().getCant_disponible(),temp.getElemento().getPrecio()};
                ModeladorTablas.nuevaFila(Tabla_Vehiculos, filaNueva);
                temp = temp.getSiguiente();
            }

        }
    }**/

    /**
     *
     * @throws Exception
     */
    public void eliminarDesdeTabla() throws Exception {
        //principal.getVehiculos().getLista_vehiculos().eliminar(Tabla_Vehiculos.getSelectedRow());
        //Tabla_Agencias.remove(Tabla_Agencias.getSelectedRow());
        this.dispose();
        
        VentGestion_Libros crear_Libro = new VentGestion_Libros(principal, rootPaneCheckingEnabled,principal);
        
       Object[] columnasLibros = new Object[] {"ID","Nombre","Tema","Descripción","Cantidad Vendida","Cantidad Disponible","Precio"};        
        crear_Libro.getTabla_Libros().setModel(ModeladorTablas.generarModeloDeTabla(7, columnasLibros));
        crear_Libro.getTabla_Libros().setAutoCreateRowSorter(false);
        //crear_Vehiculo.actualizarTabla();
        
        crear_Libro.setVisible(true);
        crear_Libro.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Libros = new javax.swing.JTable();
        jButtonCrear_Libro = new javax.swing.JButton();
        jButtonEliminar_Libro = new javax.swing.JButton();
        jButtonConsultar_Libro = new javax.swing.JButton();
        jButtonModificar_Libro = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Tabla_Libros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla_Libros);

        jButtonCrear_Libro.setText("Crear Libro");
        jButtonCrear_Libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrear_LibroActionPerformed(evt);
            }
        });

        jButtonEliminar_Libro.setText("Eliminar Libro");
        jButtonEliminar_Libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminar_LibroActionPerformed(evt);
            }
        });

        jButtonConsultar_Libro.setText("Consultar Libro");

        jButtonModificar_Libro.setText("Modificar vehículo");

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabelTitulo.setText("Gestión de Libros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1019, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCrear_Libro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEliminar_Libro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonConsultar_Libro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonModificar_Libro, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButtonCrear_Libro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButtonEliminar_Libro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonConsultar_Libro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonModificar_Libro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrear_LibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrear_LibroActionPerformed
       VentCrear_Libro crear_Libro = new VentCrear_Libro(this, rootPaneCheckingEnabled, this);
       crear_Libro.setVisible(true);
       crear_Libro.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_jButtonCrear_LibroActionPerformed

    private void jButtonEliminar_LibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminar_LibroActionPerformed
       try {

            eliminarDesdeTabla();
            

        } catch (Exception ex) {
            //ystem.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonEliminar_LibroActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_Libros;
    private javax.swing.JButton jButtonConsultar_Libro;
    private javax.swing.JButton jButtonCrear_Libro;
    private javax.swing.JButton jButtonEliminar_Libro;
    private javax.swing.JButton jButtonModificar_Libro;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
